seed : 

# True/False/auto
cuda : auto

meta:
  label: None
  conditions: None

server:
  name: None
  gpu_id: None

opt:
  optimizer : RMSProp
  alpha : 0.99 # RMSProp
  betas : [0.9, 0.999] # Adam

  lr : 3.0e-04
  eps : 1.0e-05
  max_grad_norm : 0.5
  use_scheduler: False

rl_setting:
  gamma : 0.99
  num_processes : 16 # 16
  num_steps : 5

log:
  log_interval : 100
  save_model_interval : 0

  tmp_dir : './tmp/gym/'

loss_function:
  # Num_updates = num_frames//num_steps//num_processes
  num_frames : 5.0e07
  action_loss_coef : 1.
  entropy_coef : 0.01
  value_loss_coef : 0.5

algorithm:
  use_particle_filter : False
  # BPTT for num_steps * multiplier_backprop_length
  multiplier_backprop_length : 5

  model:
    # Overwritten and set by environment yaml
    cnn_channels: None
    observation_type : None

    # Set to 0 to switch off
    action_encoding: 128

    # Set automatically to false if encoding_loss_coef==0
    resample: True

    # RNN dimension
    h_dim: 256 #  = z_dim

    encoder_batch_norm: True
    policy_batch_norm: True

    dropout: 0.1

    num_particles: 15

    particle_aggregation: mgf # options: gru, mean, mgf, mgf_noconv
    num_features: 256
